### ISSUE TITLE
Documentation unclear on how to compile for Raspberry Pi

### ISSUE THREAD

**Issue by rebroad** [unsystemizer/bitcoin-core-addrindex#1]
Would it be possible to include details of how you create the Raspberry Pi binaries please? Is cross-compilation used?

**Comment by unsystemizer** [comment]
I just follow the same procedure as Counterparty Federated Node used to do while we used to build from source (later Counterparty switched to binary builds from BTCDrak because he started releasing signed & deterministically built binaries (with Gitian)). 

The steps are the standard Bitcoin build steps and the details can be found here:
https://github.com/CounterpartyXCP/federatednode/blob/1.1.3/run.py#L282

I build these on an actual Raspberry Pi and I still build them because deterministic builds with Gitian for ARM do not exist and because it takes quite a while (few hours) to make Bitcoin Core on Raspbian. 
Once it becomes possible to build ARM arch with Gitian I will stop releasing binaries this way and build and sign multi-arch deterministic builds as per this procedure (but using BTCDrak's source because addrindex is required by CounterParty):
https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md
You can see BTCDrak's signed deterministically built releases here (note the Verified badge on the left):
https://github.com/btcdrak/bitcoin/releases

Does this answer your question?

**Comment by rebroad** [comment]
@unsystemizer yes, thank you! was hoping to find someone who has managed to get it to cross-compile faster than compiling natively on the pi though...!

**Comment by unsystemizer** [comment]
Cool. 
By the way I did succeed to cross-compile it inside of a Ubuntu 14.04 x64 VM, but getting it to work the first time was a challenge. With Pi 1 it was still worth it (especially if you have just one, and can't do anything else on it for hours), but after I got several Pi 2 it got faster and I always have one that's not heavily loaded. I thought to document the cross-build process, but later I noticed that Bitcoin intends to add ARM to its Gitian procedure so I thought it's better to wait for it.
